// <auto-generated />
using System;
using MV_Examen.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MV_Examen.Migrations
{
    [DbContext(typeof(MV_ExamenContext))]
    [Migration("20230424213308_InicioFabianaVasconez")]
    partial class InicioFabianaVasconez
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MV_Examen.Models.MF_Vasconez", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Activomf")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Cumpleañosmf")
                        .HasColumnType("datetime2");

                    b.Property<int>("Idv")
                        .HasColumnType("int");

                    b.Property<string>("Nombremf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salariomf")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("MF_Vasconez");
                });

            modelBuilder.Entity("MV_Examen.Models.VR_Fabiana", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Idv")
                        .HasColumnType("int");

                    b.Property<int?>("MF_VasconezId")
                        .HasColumnType("int");

                    b.Property<string>("Puestovr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MF_VasconezId");

                    b.ToTable("VR_Fabiana");
                });

            modelBuilder.Entity("MV_Examen.Models.VR_Fabiana", b =>
                {
                    b.HasOne("MV_Examen.Models.MF_Vasconez", "MF_Vasconez")
                        .WithMany()
                        .HasForeignKey("MF_VasconezId");

                    b.Navigation("MF_Vasconez");
                });
#pragma warning restore 612, 618
        }
    }
}
